"""initial

Revision ID: 4806569875c6
Revises: 
Create Date: 2026-05-13 18:55:17.940543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4806569875c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('texto', sa.String(length=255), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('horario_alvo', sa.String(length=10), nullable=False),
    sa.Column('frequencia', sa.String(length=50), nullable=False),
    sa.Column('lembrete', sa.Boolean(), nullable=True),
    sa.Column('antecedencia_lembrete', sa.String(length=20), nullable=True),
    sa.Column('meta_diaria', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habits')
    op.drop_table('users')
    op.drop_table('tips')
    # ### end Alembic commands ###
